image: node:11
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - build
  - deploy
  - notify

build_job:
  stage: build
  only:
    - master
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    expire_in: 30 minutes
    paths:
      - public

deploy_job:
  stage: deploy
  only:
    - master
  dependencies:
    - build_job
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan motoviaggiatori.it >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -rtv public/ gabriele@motoviaggiatori.it:/var/www/motoviaggiatori.it/

notify_job:
  stage: notify
  only:
    - master
  dependencies:
    - deploy_job
  script:
    - curl -s --user "api:$MAILGUN_API_KEY" $MAILGUN_API_URL/messages -F from="$EMAIL_FROM" -F to="$EMAIL_TO" -F subject="Deployed MotoViaggiatori" --form-string html="${CI_COMMIT_SHORT_SHA} on ${CI_COMMIT_REF_SLUG} ${CI_COMMIT_MESSAGE}"