language: node_js
node_js:
  - "stable"
branches:
  only:
  - master  
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  fqdn: motoviaggiatori.it
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_install:
  - "npm i -g gatsby"
install:
  - "npm i"
script:
  - "npm run build"
after_success:
  - "npm run deploy"