backend:
  name: github
  repo: destegabry/motoviaggiatori
  branch: v3
publish_mode: editorial_workflow
site_url: https://motoviaggiatori.it
media_folder: static/assets
public_folder: /assets
collections:
  - name: posts
    label: Post
    folder: content/post
    create: true
    slug: "{{year}}-{{month}}-fields.slug}}"
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - name: author
        label: Author
        widget: relation
        collection: authors
        value_field: title
        search_fields: [title]
      - { name: body, label: Body, widget: markdown }
  - name: authors
    label: Author
    folder: content/author
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Name }
      - { name: avatar, label: Avatar, widget: image }
      - name: links
        label: Links
        required: false
        widget: list
        fields:
        - { name: title, label: Title, required: false  }
        - { name: url, label: Url  }
      - { name: body, label: Body, widget: markdown }