backend:
  name: git-gateway
  branch: v3
  use_large_media_transforms_in_media_library: false
publish_mode: editorial_workflow
site_url: https://motoviaggiatori.it
media_folder: static/assets/uploads
public_folder: /assets
collections:
  - name: posts
    label: Blog
    label_singular: Post
    folder: content/blog
    create: true
    slug: "{{fields.path}}"
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: modified, label: Date, widget: datetime, required: false }
      - name: author
        label: Author
        widget: relation
        collection: authors
        value_field: path
        search_fields: [title, path]
        display_fields: [title]
      - name: categories
        label: Categories
        widget: relation
        collection: categories
        value_field: path
        search_fields: [title, path]
        display_fields: [title]
        multiple: true
      - name: tags
        label: Tags
        widget: relation
        collection: tags
        value_field: path
        search_fields: [title, path]
        display_fields: [title]
        multiple: true
      - { name: featured_image, label: Featured image, widget: image }
      - {
          name: featured_youtube,
          label: Featured YouTube video,
          required: false,
        }
      - { name: excerpt, label: Excerpt }
      - name: opening
        label: Opening
        widget: markdown
        required: false
      - name: disclaimer
        label: Disclaimer
        widget: markdown
        required: false
      - name: attributes
        label: Attributes
        required: false
        widget: list
        fields:
          - { name: key, label: Key }
          - { name: value, label: Value }
      - { name: body, label: Body, widget: markdown }
  - name: authors
    label: Authors
    label_singular: Author
    folder: content/authors
    create: true
    slug: "{{fields.path}}"
    fields:
      - { name: path, label: Path }
      - { name: title, label: Name }
      - { name: avatar, label: Avatar, widget: image }
      - name: links
        label: Links
        required: false
        widget: list
        fields:
          - { name: title, label: Title, required: false }
          - { name: url, label: Url }
      - { name: body, label: Body, widget: markdown }
  - name: tags
    label: Tags
    label_singular: Tag
    folder: content/tags
    create: true
    slug: "{{fields.path}}"
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown, required: false }
  - name: categories
    label: Categories
    label_singular: Category
    folder: content/categories
    create: true
    slug: "{{fields.path}}"
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown, required: false }
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    slug: "{{fields.path}}"
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: excerpt, label: Excerpt }
      - { name: body, label: Body, widget: markdown, required: false }
